# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: room_development

test:
  <<: *default
  database: room_test

production:
  <<: *default
  database: room_production
  username: room
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

